✨ Add certmanager flavor
kubernetes-sigs/cluster-api-provider-nested pull request #157
Opened 2021-07-03 19:00 UTC by charleszheng44

**What this PR does / why we need it**:
Use cert-manager to manage the PKI for the NCP components.

2021-07-03 21:26 UTC, charleszheng44 commented
/assign @christopherhein

2021-07-05 00:55 UTC, christopherhein requested changes
Overall looks good but I think we need to set longer expiries on the client certs like the default config.

2021-07-05 00:55 UTC, christopherhein commented on templates/cluster-template-certmanager.yaml
> +  renewBefore: 360h # 15d
```suggestion
  duration: 8760h # 1y
  renewBefore: 4380h # 6m
```

To mirror CAPI and the default setup can we set this to 1 year and 6months?

2021-07-05 00:55 UTC, christopherhein commented on templates/cluster-template-certmanager.yaml
> +  renewBefore: 360h # 15d
```suggestion
  duration: 8760h # 1y
  renewBefore: 4380h # 6m
```

2021-07-05 00:55 UTC, christopherhein commented on templates/cluster-template-certmanager.yaml
> +  renewBefore: 360h # 15d
```suggestion
  duration: 8760h # 1y
  renewBefore: 4380h # 6m
```

2021-07-05 20:12 UTC, charleszheng44 commented
> Overall looks good but I think we need to set longer expiries on the client certs like the default config.

Just prolong the expiries.

2021-07-06 00:45 UTC, christopherhein approved these changes
🎉 

Nice work!
/lgtm

2021-07-06 00:46 UTC, merged