📖Add info about usage of kubectl vc exec
kubernetes-sigs/cluster-api-provider-nested pull request #174
Opened 2021-07-13 05:27 UTC by jichenjc

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #169

2021-07-13 19:45 UTC, christopherhein requested changes
couple of small grammatical issues otherwise looks great.

2021-07-13 19:45 UTC, christopherhein commented on virtualcluster/doc/demo.md
> +You can use `kubectl vc exec` to operator on desired cluster, for example:
```suggestion
You can use `kubectl vc exec` to operate on desired virtualcluster, for example:
```

2021-07-13 19:45 UTC, christopherhein commented on virtualcluster/doc/demo.md
> +Also, the kubeconfig is generated at `/home/cloudusr/.kube/vc/` with name `<namespace>-<cluster name>.kubeconfig`, in our example, it'
```suggestion
Also, the kubeconfig is generated and stored at `~/.kube/vc/` with name `<namespace>-<cluster name>.kubeconfig`, in our example, it's
```

2021-07-13 19:45 UTC, christopherhein commented on virtualcluster/doc/demo.md
> + `/home/cloudusr/.kube/vc/default-b9bf25-vc-sample-1.kubeconfig`, you can use it if the original kubeconfig is lost.
```suggestion
 `~/.kube/vc/default-b9bf25-vc-sample-1.kubeconfig`, you can use it if the original kubeconfig is lost.
```

2021-07-14 04:02 UTC, christopherhein commented on virtualcluster/doc/demo.md
> +## (Optional) use `kubectl vc exec` to enter cluster context and regenerate kubeconfig for paticular virtualcluster
missed one more thing, thank you!

```suggestion
## (Optional) use `kubectl vc exec` to enter cluster context and regenerate kubeconfig for particular virtualcluster
```

2021-07-14 04:09 UTC, jichenjc commented on virtualcluster/doc/demo.md
> +## (Optional) use `kubectl vc exec` to enter cluster context and regenerate kubeconfig for paticular virtualcluster
done :)

2021-07-14 04:10 UTC, christopherhein commented
/lgtm
/approve

2021-07-14 04:22 UTC, merged