[WIP] NestedControlPlane & NestedCluster Controllers
kubernetes-sigs/cluster-api-provider-nested pull request #43
Opened 2021-05-04 16:54 UTC by christopherhein

> **This is still a work in progress**

This PR adds in the NCP and NC controllers for orchestrating the control plane creation by setting up all PKI and creating necessary components.

## TODO:
- [x] Create NestedControlPlane controller
- [x] Create NestedCluster controller
- [x] Generate CAs for all components
- [x] Generate client certs from component CAs
- [x] Setup status management
- [x] Verify `clusterctl` works for `kubeconfigs`
- [ ] Write tests

2021-05-05 14:26 UTC, christopherhein commented
/assign @charleszheng44 @Fei-Guo

2021-05-06 00:24 UTC, Fei-Guo commented
LGTM. I will leave Chao to give another pass.

2021-05-06 04:01 UTC, charleszheng44 requested changes

2021-05-06 04:04 UTC, christopherhein commented on config/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
> +        - mountPath: /etc/kubernetes/pki/proxy/ca
Not with how it's configured in here right now. I can remove this.

2021-05-06 04:08 UTC, charleszheng44 approved these changes
LGTM

2021-05-06 04:09 UTC, christopherhein commented on config/component-templates/nested-apiserver/nested-apiserver-statefulset-template.yaml
> +        - mountPath: /etc/kubernetes/pki/proxy/ca
Updated and removed these unused mounts.

2021-05-06 04:10 UTC, charleszheng44 commented
lgtm

2021-05-06 04:14 UTC, charleszheng44 commented
/lgtm

2021-05-06 04:15 UTC, merged